apiVersion: v1
kind: ReplicationController
metadata:
  name: new-rc
spec:
  template:
    metadata:
      name: new-pod
      labels:
        env: test
        dc: mum
    spec:
      containers:
        - image: nginx
          name: nginximage
  replicas: 4
  selector: # This acts like an and operator
    env: test
    dc: mum